#!/bin/sh
# render-litellm-config.sh — turn config/models.json (the real, hand-maintained catalog of what
# this server serves) into litellm's config.yaml: one real model_list entry per real model id, so
# GET /v1/models reports actual model names instead of a wildcard placeholder. Every entry routes
# through reasoning-normalizer, which resolves the real id against the SAME catalog (MODELS_FILE)
# to the right backend server/node and applies its dual-delta SSE fix regardless of backend.
#
# Also probes each model's own backend (the raw vLLM url in models.json) for its real metadata
# (max_model_len, root — whatever GET <backend>/v1/models reports) and embeds it as `model_info`
# on that model's litellm entry. Plain GET /v1/models on litellm still can't show this (fixed by
# the OpenAI spec: id/object/created/owned_by only, see ideas/model-catalog-configurator.md's
# 2026-09-10 correction) — but GET /model/info DOES expose model_info, so this is what makes a
# client's probe get the same data through this server as it would querying the backend directly.
#
# Runs once, at server startup, before litellm (see compose.yml's catalog-render service +
# litellm's depends_on: condition: service_completed_successfully). POSIX sh + jq + curl only —
# no bash, no yq — so a minimal alpine image can run it with one apk install.
set -eu

CATALOG="${CATALOG:-/config/models.json}"
OUT="${OUT:-/out/litellm-config.yaml}"
PROBE_TIMEOUT="${PROBE_TIMEOUT:-5}"

[ -s "$CATALOG" ] || { echo ">>> render-litellm-config: no catalog at $CATALOG" >&2; exit 1; }
command -v jq >/dev/null || { echo ">>> render-litellm-config: jq missing" >&2; exit 1; }
command -v curl >/dev/null || { echo ">>> render-litellm-config: curl missing" >&2; exit 1; }

# One "url<TAB>server<TAB>alias<TAB>real_id<TAB>reasoning_effort" line per model — url is that
# model's OWN backend, needed to probe it directly. `server` is the catalog's own grouping key
# (e.g. "spark01"), carried through into model_info purely as a display label — litellm itself has
# no server/node concept, everything routes through the single reasoning-normalizer regardless.
# `alias` is the litellm model_name clients pick (the catalog key); `real_id` is what's actually
# requested from vLLM (defaults to `alias` via `serves_as`) — the two differ only for
# reasoning-effort variants, where several aliases (e.g. "glm-low"/"glm-high") all point at the
# SAME underlying served model, each with its own baked-in `reasoning_effort` in litellm_params so
# picking a "model" in the client is really picking an effort tier.
pairs="$(jq -r '.servers // {} | to_entries[] | .key as $srv | .value.url as $u | (.value.models // {}) | to_entries[] |
  "\($u)\t\($srv)\t\(.key)\t\(.value.serves_as // .key)\t\(.value.reasoning_effort // "")"' "$CATALOG" | sort -u)"
[ -n "$pairs" ] || { echo ">>> render-litellm-config: catalog has no models — nothing to render" >&2; exit 1; }

# model_info_for <url> <real_id> -> a "key: value" YAML fragment (2 lines, already indented) or
# empty. Probed by real_id (what the backend actually serves), never by alias. Best-effort: a
# backend that's briefly unreachable at render time just yields no extra metadata for that model
# this run — it does not fail the whole render (a client falls back to typing the context in by
# hand either way, same as today).
model_info_for() {
  url="$1"; real_id="$2"
  body="$(curl -fsS -m "$PROBE_TIMEOUT" "$url/models" 2>/dev/null)" || { echo ""; return 0; }
  echo "$body" | jq -r --arg id "$real_id" '
    (.data // [])[] | select(.id == $id) |
    [ (if .max_model_len then "      max_model_len: \(.max_model_len)" else empty end),
      (if .root then "      root: \"\(.root)\"" else empty end) ] |
    join("\n")
  ' 2>/dev/null || echo ""
}

count=0
{
  echo "# GENERATED by render-litellm-config.sh from $CATALOG — do not hand-edit, it is overwritten"
  echo "# on every server start. Edit models.json instead. See ../ideas/model-catalog-configurator.md."
  echo "model_list:"
  echo "$pairs" | while IFS="$(printf '\t')" read -r url srv alias real_id effort; do
    [ -n "$alias" ] || continue
    printf '  - model_name: "%s"\n' "$alias"
    printf '    litellm_params:\n'
    printf '      model: "hosted_vllm/%s"\n' "$real_id"
    printf '      api_base: "os.environ/LITELLM_UPSTREAM"\n'
    printf '      api_key: dummy\n'
    if [ -n "$effort" ]; then
      printf '      reasoning_effort: "%s"\n' "$effort"
    fi
    info="$(model_info_for "$url" "$real_id")"
    printf '    model_info:\n'
    printf '      server: "%s"\n' "$srv"
    if [ -n "$info" ]; then
      printf '%s\n' "$info"
    fi
  done
  cat <<'EOF'

litellm_settings:
  drop_params: true                 # silently drop unsupported params (thinking, effort, etc.) instead of erroring
  use_responses_api: false
  forward_client_headers_to_llm_api: false
  # Upstream read timeout. Default 600s kills a long single generation: on a slow box a maxed
  # reasoning+content turn (8k think + 16k content) at ~44 tok/s is ~9 min, so 600s cuts it off
  # mid-stream ("Timeout on reading data from socket"). 3600s matches the rest of the timeout chain
  # (claude-shim + reasoning-normalizer UPSTREAM_TIMEOUT_MS, Claude Code API_TIMEOUT_MS).
  request_timeout: 3600
EOF
} > "$OUT"

count="$(echo "$pairs" | wc -l | tr -d ' ')"
echo "> rendered $count model(s) into $OUT (GET /model/info carries per-model metadata where the backend answered)"
